
services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
  # app:
  #   build:
  #     context: .
  #   image: nextjs-devdemo
  #   ports:
  #     - "3000:3000"
  #   environment:
  #      NODE_ENV: development
  #   develop:
  #     watch:
  #       - action: sync
  #         path: ./
  #         target: /app/src
  #         ignore:
  #           - node_modules/
  #           - .git/
  #           - .next/
  #       - action: rebuild
  #         path: package.json